# Generated by Django 3.0.2 on 2020-01-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20200120_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
